# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_response.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14login_response.proto\x1a\x19google/protobuf/any.proto\"J\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\"\xf1\x01\n\rLoginResponse\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x15.LoginResponse.Result\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x16\n\x0eis_initialized\x18\x05 \x01(\x08\x12\x19\n\x11large_init_packet\x18\x06 \x01(\x0c\"O\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_TOKEN\x10\x01\x12\x15\n\x11\x41LREADY_CONNECTED\x10\x02\x12\x13\n\x0fINVALID_VERSION\x10\x03\"\x18\n\tNDAStatus\x12\x0b\n\x03nda\x18\x01 \x01(\x08\"\x1e\n\x04Pong\x12\x16\n\x0eserver_time_ms\x18\x01 \x01(\x05\x32\x38\n\x0eGatewayService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=51
  _globals['_LOGINREQUEST']._serialized_end=125
  _globals['_LOGINRESPONSE']._serialized_start=128
  _globals['_LOGINRESPONSE']._serialized_end=369
  _globals['_LOGINRESPONSE_RESULT']._serialized_start=290
  _globals['_LOGINRESPONSE_RESULT']._serialized_end=369
  _globals['_NDASTATUS']._serialized_start=371
  _globals['_NDASTATUS']._serialized_end=395
  _globals['_PONG']._serialized_start=397
  _globals['_PONG']._serialized_end=427
  _globals['_GATEWAYSERVICE']._serialized_start=429
  _globals['_GATEWAYSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
