# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login_response.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'login_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14login_response.proto\"m\n\rLoginResponse\x12%\n\x06result\x18\x01 \x02(\x0e\x32\x15.LoginResponse_Result\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t*]\n\x14LoginResponse_Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_TOKEN\x10\x01\x12\x15\n\x11\x41LREADY_CONNECTED\x10\x02\x12\x13\n\x0fINVALID_VERSION\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINRESPONSE_RESULT']._serialized_start=135
  _globals['_LOGINRESPONSE_RESULT']._serialized_end=228
  _globals['_LOGINRESPONSE']._serialized_start=24
  _globals['_LOGINRESPONSE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
