# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login_response.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'login_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14login_response.proto\x1a\x19google/protobuf/any.proto\"h\n\x0eGatewayRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x03 \x01(\x03\"x\n\x0fGatewayResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\"I\n\x0cLoginRequest\x12\x11\n\tjwt_token\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\"\x92\x01\n\rLoginResponse\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x15.LoginResponse.Result\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"#\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_TOKEN\x10\x01\"\x1b\n\nNDARequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1a\n\x0bNDAResponse\x12\x0b\n\x03nda\x18\x01 \x01(\x08\"\x1e\n\x04Pong\x12\x16\n\x0eserver_time_ms\x18\x01 \x01(\x03\x32\x38\n\x0eGatewayService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse23\n\nNDAService\x12%\n\x08\x43heckNDA\x12\x0b.NDARequest\x1a\x0c.NDAResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEWAYREQUEST']._serialized_start=51
  _globals['_GATEWAYREQUEST']._serialized_end=155
  _globals['_GATEWAYRESPONSE']._serialized_start=157
  _globals['_GATEWAYRESPONSE']._serialized_end=277
  _globals['_LOGINREQUEST']._serialized_start=279
  _globals['_LOGINREQUEST']._serialized_end=352
  _globals['_LOGINRESPONSE']._serialized_start=355
  _globals['_LOGINRESPONSE']._serialized_end=501
  _globals['_LOGINRESPONSE_RESULT']._serialized_start=466
  _globals['_LOGINRESPONSE_RESULT']._serialized_end=501
  _globals['_NDAREQUEST']._serialized_start=503
  _globals['_NDAREQUEST']._serialized_end=530
  _globals['_NDARESPONSE']._serialized_start=532
  _globals['_NDARESPONSE']._serialized_end=558
  _globals['_PONG']._serialized_start=560
  _globals['_PONG']._serialized_end=590
  _globals['_GATEWAYSERVICE']._serialized_start=592
  _globals['_GATEWAYSERVICE']._serialized_end=648
  _globals['_NDASERVICE']._serialized_start=650
  _globals['_NDASERVICE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
