# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x12\x04room\"B\n\nRoomPlayer\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07team_id\x18\x03 \x01(\x05\"@\n\tRoomSquad\x12\x10\n\x08squad_id\x18\x01 \x01(\t\x12!\n\x07members\x18\x02 \x03(\x0b\x32\x10.room.RoomPlayer\"\x86\x01\n\x08RoomInfo\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x10\n\x08map_name\x18\x02 \x01(\t\x12\x13\n\x0bmax_players\x18\x03 \x01(\x05\x12!\n\x07players\x18\x04 \x03(\x0b\x32\x10.room.RoomPlayer\x12\x1f\n\x06squads\x18\x05 \x03(\x0b\x32\x0f.room.RoomSquad\"&\n\x07\x43onnect\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\"Y\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0froom_session_id\x18\x02 \x01(\t\x12\x1c\n\x04info\x18\x03 \x01(\x0b\x32\x0e.room.RoomInfo\"*\n\x14ResetAllWaitingRooms\x12\x12\n\nreset_done\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMPLAYER']._serialized_start=20
  _globals['_ROOMPLAYER']._serialized_end=86
  _globals['_ROOMSQUAD']._serialized_start=88
  _globals['_ROOMSQUAD']._serialized_end=152
  _globals['_ROOMINFO']._serialized_start=155
  _globals['_ROOMINFO']._serialized_end=289
  _globals['_CONNECT']._serialized_start=291
  _globals['_CONNECT']._serialized_end=329
  _globals['_CONNECTRESPONSE']._serialized_start=331
  _globals['_CONNECTRESPONSE']._serialized_end=420
  _globals['_RESETALLWAITINGROOMS']._serialized_start=422
  _globals['_RESETALLWAITINGROOMS']._serialized_end=464
# @@protoc_insertion_point(module_scope)
